import { Font, Template, CardData } from './types';

export const FONTS: Font[] = [
  { name: 'Inter', value: '"Inter", sans-serif' },
  { name: 'Merriweather', value: '"Merriweather", serif' },
  { name: 'Inconsolata', value: '"Inconsolata", monospace' },
  { name: 'Montserrat', value: '"Montserrat", sans-serif' },
  { name: 'Lato', value: '"Lato", sans-serif' },
  { name: 'Open Sans', value: '"Open Sans", sans-serif' },
  { name: 'Playfair Display', value: '"Playfair Display", serif' },
  { name: 'Roboto', value: '"Roboto", sans-serif' },
];

export const DEFAULT_CARD_DATA: CardData = {
  name: 'Your Name',
  title: 'Your Title',
  company: 'Your Company',
  phone: '(123) 456-7890',
  email: 'hello@example.com',
  website: 'yourwebsite.com',
  address: '123 Main St, Anytown, USA',
  fontFamily: 'Inter',
  textColor: '#111827',
  backgroundColor: '#ffffff',
  layout: 'left',
};

export const SVG_TEMPLATES: Template[] = [
  // --- Corporate & Clean (Uses template_1.svg, template_2.svg, template_6.svg, template_12.svg, template_20.svg) ---
  { name: 'Classic Blue', file: 'template_1.svg', data: { fontFamily: 'Lato', backgroundColor: '#eef2ff', textColor: '#1e3a8a', layout: 'left' } },
  { name: 'Executive White', file: 'template_2.svg', data: { fontFamily: 'Open Sans', backgroundColor: '#ffffff', textColor: '#111827', layout: 'left' } },
  { name: 'Minimal Sand', file: 'template_6.svg', data: { fontFamily: 'Open Sans', backgroundColor: '#fdfdfd', textColor: '#57534e', layout: 'left' } },
  { name: 'White & Black', file: 'template_12.svg', data: { fontFamily: 'Open Sans', backgroundColor: '#ffffff', textColor: '#000000', layout: 'left' } },
  { name: 'Professional Teal', file: 'template_20.svg', data: { fontFamily: 'Roboto', backgroundColor: '#f0f9ff', textColor: '#155e75', layout: 'left' } },
  { name: 'Light Gray', file: 'template_2.svg', data: { fontFamily: 'Inter', backgroundColor: '#f9fafb', textColor: '#1f2937', layout: 'left' } },
  { name: 'Steel Blue', file: 'template_1.svg', data: { fontFamily: 'Lato', backgroundColor: '#e0e7ff', textColor: '#3730a3', layout: 'left' } },
  { name: 'Simple Navy', file: 'template_1.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#eef2ff', textColor: '#1e40af', layout: 'left' } },
  { name: 'Clean Slate', file: 'template_6.svg', data: { fontFamily: 'Roboto', backgroundColor: '#f8fafc', textColor: '#334155', layout: 'left' } },
  { name: 'Corporate Green', file: 'template_20.svg', data: { fontFamily: 'Open Sans', backgroundColor: '#f0fdf4', textColor: '#166534', layout: 'left' } },
  { name: 'Off-White', file: 'template_2.svg', data: { fontFamily: 'Lato', backgroundColor: '#fefcfb', textColor: '#44403c', layout: 'left' } },
  { name: 'Sky Blue', file: 'template_1.svg', data: { fontFamily: 'Inter', backgroundColor: '#f0f9ff', textColor: '#0369a1', layout: 'left' } },
  { name: 'Modern Mint', file: 'template_20.svg', data: { fontFamily: 'Roboto', backgroundColor: '#f0fdfa', textColor: '#0f766e', layout: 'left' } },
  { name: 'Stone Gray', file: 'template_6.svg', data: { fontFamily: 'Lato', backgroundColor: '#fafafa', textColor: '#525252', layout: 'left' } },

  // --- Bold & Creative (Uses template_3.svg, template_4.svg, template_9.svg, template_17.svg) ---
  { name: 'Vibrant Orange', file: 'template_3.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#ffedd5', textColor: '#c2410c', layout: 'center' } },
  { name: 'Creative Fuchsia', file: 'template_4.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#fdf4ff', textColor: '#a21caf', layout: 'center' } },
  { name: 'Slate & Cyan', file: 'template_9.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#334155', textColor: '#67e8f9', layout: 'left' } },
  { name: 'Bold Red', file: 'template_17.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#fee2e2', textColor: '#b91c1c', layout: 'center' } },
  { name: 'Sunshine', file: 'template_10.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#fef3c7', textColor: '#92400e', layout: 'left' } },
  { name: 'Aqua Fresh', file: 'template_11.svg', data: { fontFamily: 'Roboto', backgroundColor: '#ecfeff', textColor: '#0891b2', layout: 'center' } },
  { name: 'Lime Punch', file: 'template_3.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#f7fee7', textColor: '#4d7c0f', layout: 'center' } },
  { name: 'Deep Purple', file: 'template_4.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#f5f3ff', textColor: '#5b21b6', layout: 'center' } },
  { name: 'Hot Pink', file: 'template_4.svg', data: { fontFamily: 'Lato', backgroundColor: '#fdf2f8', textColor: '#be185d', layout: 'center' } },
  { name: 'Electric Blue', file: 'template_9.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#1e293b', textColor: '#2563eb', layout: 'left' } },
  { name: 'Forest & Lime', file: 'template_9.svg', data: { fontFamily: 'Roboto', backgroundColor: '#1a2e05', textColor: '#a3e635', layout: 'left' } },
  { name: 'Crimson Wave', file: 'template_17.svg', data: { fontFamily: 'Lato', backgroundColor: '#1e293b', textColor: '#dc2626', layout: 'center' } },
  { name: 'Amber Glow', file: 'template_3.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#fffbeb', textColor: '#b45309', layout: 'center' } },
  { name: 'Teal Splash', file: 'template_11.svg', data: { fontFamily: 'Roboto', backgroundColor: '#f0fdfa', textColor: '#0d9488', layout: 'center' } },
  { name: 'Indigo Dream', file: 'template_9.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#1e1b4b', textColor: '#a5b4fc', layout: 'left' } },

  // --- Elegant & Minimal (Uses template_5.svg, template_8.svg, template_15.svg) ---
  { name: 'Rose Gold', file: 'template_5.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#fff1f2', textColor: '#881337', layout: 'center' } },
  { name: 'Black & Gold', file: 'template_8.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#171717', textColor: '#fde047', layout: 'center' } },
  { name: 'Luxury Script', file: 'template_15.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#1c1917', textColor: '#fef3c7', layout: 'center' } },
  { name: 'Gilded Onyx', file: 'template_8.svg', data: { fontFamily: 'Merriweather', backgroundColor: '#000000', textColor: '#ca8a04', layout: 'center' } },
  { name: 'Silver Charm', file: 'template_8.svg', data: { fontFamily: 'Lato', backgroundColor: '#1f2937', textColor: '#d1d5db', layout: 'center' } },
  { name: 'Ruby Red', file: 'template_5.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#fef2f2', textColor: '#991b1b', layout: 'center' } },
  { name: 'Emerald', file: 'template_15.svg', data: { fontFamily: 'Merriweather', backgroundColor: '#064e3b', textColor: '#d1fae5', layout: 'center' } },
  { name: 'Sapphire', file: 'template_15.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#1e40af', textColor: '#dbeafe', layout: 'center' } },
  { name: 'Pearl White', file: 'template_5.svg', data: { fontFamily: 'Merriweather', backgroundColor: '#f9fafb', textColor: '#1f2937', layout: 'center' } },
  { name: 'Copperplate', file: 'template_8.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#292524', textColor: '#f97316', layout: 'center' } },
  { name: 'Garnet', file: 'template_15.svg', data: { fontFamily: 'Lato', backgroundColor: '#4a044e', textColor: '#fdf4ff', layout: 'center' } },
  
  // --- Dark & Modern (Uses template_7.svg, template_13.svg, template_19.svg) ---
  { name: 'Deep Indigo', file: 'template_7.svg', data: { fontFamily: 'Lato', backgroundColor: '#312e81', textColor: '#e0e7ff', layout: 'left' } },
  { name: 'Gradient Tech', file: 'template_13.svg', data: { fontFamily: 'Inter', backgroundColor: '#2b2244', textColor: '#e9d5ff', layout: 'left' } },
  { name: 'Geometric Dark', file: 'template_19.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#1f2937', textColor: '#d1d5db', layout: 'center' } },
  { name: 'Midnight Blue', file: 'template_7.svg', data: { fontFamily: 'Roboto', backgroundColor: '#1e1b4b', textColor: '#c7d2fe', layout: 'left' } },
  { name: 'Charcoal', file: 'template_19.svg', data: { fontFamily: 'Open Sans', backgroundColor: '#262626', textColor: '#a3a3a3', layout: 'center' } },
  { name: 'Cyber Purple', file: 'template_13.svg', data: { fontFamily: 'Inconsolata', backgroundColor: '#281c3b', textColor: '#c084fc', layout: 'left' } },
  { name: 'Dark Slate', file: 'template_7.svg', data: { fontFamily: 'Lato', backgroundColor: '#0f172a', textColor: '#94a3b8', layout: 'left' } },
  { name: 'Night Rider', file: 'template_19.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#18181b', textColor: '#a1a1aa', layout: 'center' } },
  { name: 'Matrix Green', file: 'template_13.svg', data: { fontFamily: 'Inconsolata', backgroundColor: '#020617', textColor: '#4ade80', layout: 'left' } },
  { name: 'Volcano', file: 'template_7.svg', data: { fontFamily: 'Roboto', backgroundColor: '#4a044e', textColor: '#f472b6', layout: 'left' } },
  { name: 'Deep Space', file: 'template_13.svg', data: { fontFamily: 'Inter', backgroundColor: '#111827', textColor: '#9ca3af', layout: 'left' } },
  { name: 'Asphalt', file: 'template_19.svg', data: { fontFamily: 'Lato', backgroundColor: '#3f3f46', textColor: '#e5e5e5', layout: 'center' } },
  
  // --- Natural & Earthy (Uses template_14.svg, template_18.svg, template_16.svg) ---
  { name: 'Earthy Green', file: 'template_14.svg', data: { fontFamily: 'Lato', backgroundColor: '#f0fdf4', textColor: '#166534', layout: 'left' } },
  { name: 'Pastel Mint', file: 'template_18.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#f0fdfa', textColor: '#134e4a', layout: 'center' } },
  { name: 'Corner Accent', file: 'template_16.svg', data: { fontFamily: 'Roboto', backgroundColor: '#f8fafc', textColor: '#475569', layout: 'left' } },
  { name: 'Desert Sand', file: 'template_14.svg', data: { fontFamily: 'Merriweather', backgroundColor: '#fefce8', textColor: '#854d0e', layout: 'left' } },
  { name: 'Ocean Mist', file: 'template_18.svg', data: { fontFamily: 'Lato', backgroundColor: '#f0f9ff', textColor: '#0c4a6e', layout: 'center' } },
  { name: 'Terracotta', file: 'template_16.svg', data: { fontFamily: 'Roboto', backgroundColor: '#fef2f2', textColor: '#991b1b', layout: 'left' } },
  { name: 'Forest Floor', file: 'template_14.svg', data: { fontFamily: 'Open Sans', backgroundColor: '#f1f5f9', textColor: '#1e293b', layout: 'left' } },
  { name: 'Lavender', file: 'template_18.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#f5f3ff', textColor: '#5b21b6', layout: 'center' } },
  { name: 'River Stone', file: 'template_16.svg', data: { fontFamily: 'Lato', backgroundColor: '#f4f4f5', textColor: '#52525b', layout: 'left' } },
  { name: 'Clay', file: 'template_14.svg', data: { fontFamily: 'Roboto', backgroundColor: '#fff7ed', textColor: '#9a3412', layout: 'left' } },
  { name: 'Sky', file: 'template_18.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#eff6ff', textColor: '#1e40af', layout: 'center' } },
  { name: 'Rose', file: 'template_16.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#fff1f2', textColor: '#9f1239', layout: 'left' } },
  
  // --- Mix & Match for volume ---
  { name: 'Tech Orange', file: 'template_13.svg', data: { fontFamily: 'Inconsolata', backgroundColor: '#1c1917', textColor: '#fb923c', layout: 'left' } },
  { name: 'Walnut', file: 'template_14.svg', data: { fontFamily: 'Merriweather', backgroundColor: '#fef3c7', textColor: '#78350f', layout: 'left' } },
  { name: 'Royal', file: 'template_15.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#1e3a8a', textColor: '#f0f9ff', layout: 'center' } },
  { name: 'Graphite', file: 'template_16.svg', data: { fontFamily: 'Roboto', backgroundColor: '#e2e8f0', textColor: '#1e293b', layout: 'left' } },
  { name: 'Cherry Blossom', file: 'template_18.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#fdf2f8', textColor: '#9d174d', layout: 'center' } },
  { name: 'Deep Forest', file: 'template_19.svg', data: { fontFamily: 'Lato', backgroundColor: '#0f172a', textColor: '#a3e635', layout: 'center' } },
  { name: 'Ocean Blue', file: 'template_20.svg', data: { fontFamily: 'Roboto', backgroundColor: '#e0f2fe', textColor: '#075985', layout: 'left' } },
  { name: 'Soft Peach', file: 'template_3.svg', data: { fontFamily: 'Lato', backgroundColor: '#fff7ed', textColor: '#c2410c', layout: 'center' } },
  { name: 'Regal Purple', file: 'template_5.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#faf5ff', textColor: '#581c87', layout: 'center' } },
  { name: 'Midnight Gold', file: 'template_8.svg', data: { fontFamily: 'Merriweather', backgroundColor: '#1e293b', textColor: '#facc15', layout: 'center' } },
  { name: 'Ice Cool', file: 'template_11.svg', data: { fontFamily: 'Roboto', backgroundColor: '#f1f5f9', textColor: '#0891b2', layout: 'center' } },
  { name: 'Sunny Day', file: 'template_1.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#fefce8', textColor: '#a16207', layout: 'left' } },
  { name: 'Crimson Night', file: 'template_7.svg', data: { fontFamily: 'Lato', backgroundColor: '#1f2937', textColor: '#ef4444', layout: 'left' } },
  { name: 'Gold Standard', file: 'template_15.svg', data: { fontFamily: 'Merriweather', backgroundColor: '#18181b', textColor: '#eab308', layout: 'center' } },
  { name: 'Mint Chocolate', file: 'template_19.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#27272a', textColor: '#a7f3d0', layout: 'center' } },
  { name: 'Plum', file: 'template_13.svg', data: { fontFamily: 'Inter', backgroundColor: '#f5f3ff', textColor: '#6d28d9', layout: 'left' } },
  { name: 'Rosewater', file: 'template_16.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#fef2f2', textColor: '#be123c', layout: 'left' } },
  { name: 'Sandstone', file: 'template_14.svg', data: { fontFamily: 'Lato', backgroundColor: '#fdf4ff', textColor: '#7e22ce', layout: 'left' } },
  { name: 'Olive', file: 'template_18.svg', data: { fontFamily: 'Open Sans', backgroundColor: '#f7fee7', textColor: '#3f6212', layout: 'center' } },
  { name: 'Tangerine', file: 'template_17.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#fff7ed', textColor: '#ea580c', layout: 'center' } },
  { name: 'Blue Jay', file: 'template_20.svg', data: { fontFamily: 'Roboto', backgroundColor: '#e0f2fe', textColor: '#0284c7', layout: 'left' } },
  { name: 'Mocha', file: 'template_6.svg', data: { fontFamily: 'Merriweather', backgroundColor: '#fafaf9', textColor: '#44403c', layout: 'left' } },
  { name: 'Magenta', file: 'template_4.svg', data: { fontFamily: 'Lato', backgroundColor: '#fdf4ff', textColor: '#c026d3', layout: 'center' } },
  { name: 'Mustard', file: 'template_10.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#fefce8', textColor: '#ca8a04', layout: 'left' } },
  { name: 'Storm', file: 'template_7.svg', data: { fontFamily: 'Open Sans', backgroundColor: '#475569', textColor: '#e2e8f0', layout: 'left' } },
  { name: 'Periwinkle', file: 'template_1.svg', data: { fontFamily: 'Lato', backgroundColor: '#eef2ff', textColor: '#4f46e5', layout: 'left' } },
  { name: 'Classic Dark', file: 'template_2.svg', data: { fontFamily: 'Open Sans', backgroundColor: '#1f2937', textColor: '#f3f4f6', layout: 'left' } },
  { name: 'Orange Soda', file: 'template_3.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#fff7ed', textColor: '#f97316', layout: 'center' } },
  { name: 'Pink Salt', file: 'template_5.svg', data: { fontFamily: 'Playfair Display', backgroundColor: '#fdf2f8', textColor: '#db2777', layout: 'center' } },
  { name: 'Nightshade', file: 'template_15.svg', data: { fontFamily: 'Merriweather', backgroundColor: '#1e1b4b', textColor: '#a78bfa', layout: 'center' } },
  { name: 'Azure', file: 'template_11.svg', data: { fontFamily: 'Roboto', backgroundColor: '#f0f9ff', textColor: '#0ea5e9', layout: 'center' } },
  { name: 'Lemonade', file: 'template_10.svg', data: { fontFamily: 'Montserrat', backgroundColor: '#fef9c3', textColor: '#854d0e', layout: 'left' } },
  { name: 'Marine', file: 'template_9.svg', data: { fontFamily: 'Lato', backgroundColor: '#0c4a6e', textColor: '#bae6fd', layout: 'left' } },
];
